# DO NOT CHANGE -> WILL BREAK copier LOGIC
_commit: v0.9.6
_src_path: /home/linauerl/git/bot_template
author_mail: lukas.linauer@ait.ac.at
description: A Bot classifying News Items into Cybersecurity/Non-Cybersecurity
models: cybersec_mlp, bart_mnli
project_name: cybersec-classifier
repo_url: https://github.com/taranis-ai/cybersec-classifier
