# DO NOT CHANGE -> WILL BREAK copier LOGIC
_commit: v0.9.0
_src_path: https://github.com/taranis-ai/bot_template
author_mail: lukas.linauer@ait.ac.at
description: A Bot classifying News Items into Cybersecurity/Non-Cybersecurity
init_git_repo: true
models: cybersec_mlp, bart_mnli
project_name: cybersec-classifier
repo_url: https://github.com/taranis-ai/cybersec-classifier
